version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $ECR_REPO:$CIRCLE_SHA1 .
      - run:
          name: Push Image to ECR
          command: |
            echo "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY" | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            docker tag $ECR_REPO:$CIRCLE_SHA1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$CIRCLE_SHA1
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$CIRCLE_SHA1

workflows:
  version: 2
  project-workflow:
    jobs:
      - build:
          context: org-global  # Asegúrate de que este contexto contenga las variables de entorno necesarias
