version: 2.1

jobs:
  build:
    docker:
      - image: cimg/aws-cli  # Cambiado a la imagen que incluye AWS CLI
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Print Environment Variables
          command: |
            echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
            echo "AWS_REGION: $AWS_REGION"
            echo "ECR_REPO: $ECR_REPO"
      - run:
          name: Build Docker Image
          command: |
            docker build -t $ECR_REPO:$CIRCLE_SHA1 .
      - run:
          name: Push Image to ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
            docker tag $ECR_REPO:$CIRCLE_SHA1 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$CIRCLE_SHA1
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:$CIRCLE_SHA1

workflows:
  version: 2
  project-workflow:
    jobs:
      - build:
          context: org-global  # Asegúrate de que este contexto contenga las variables de entorno necesarias
